{{- if .Extra.IngressEnabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Name }}-{{ .Component }}
  namespace: {{ .Namespace }}
  labels:
    {{- range $key, $value := .Labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- if .Extra.IngressAnnotations }}
  annotations:
    {{- range $key, $value := .Extra.IngressAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Extra.IngressClassName }}
  ingressClassName: {{ .Extra.IngressClassName }}
  {{- end }}
  {{- if .Extra.TLS }}
  tls:
    {{- range .Extra.TLS }}
    - hosts:
        {{- range .Hosts }}
        - {{ . }}
        {{- end }}
      {{- if .SecretName }}
      secretName: {{ .SecretName }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Extra.IngressHost }}
    - host: {{ .Extra.IngressHost }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Name }}-{{ .Component }}
                port:
                  {{- if .Extra.TLS }}
                  name: https
                  {{- else }}
                  name: http
                  {{- end }}
{{- end }}
