{{- if .Extra.Enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Name }}-{{ .Component }}-server
  namespace: {{ .Namespace }}
  labels:
    {{- range $key, $value := .Labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- if .Annotations }}
  annotations:
    {{- range $key, $value := .Annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
