apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}-{{ .Component }}
  namespace: {{ .Namespace }}
  labels:
    {{- range $key, $value := .Labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: argocd-redis
    app.kubernetes.io/instance: {{ .Name }}
    app.kubernetes.io/component: {{ .Component }}
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
