apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}-{{ .Component }}
  namespace: {{ .Namespace }}
  labels:
    {{- range $key, $value := .Labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Extra.ServiceType | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/instance: {{ .Name }}
    app.kubernetes.io/component: {{ .Component }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8083
