apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}-{{ .Component }}
  namespace: {{ .Namespace }}
  labels:
    {{- range $key, $value := .Labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: argocd-applicationset-controller
    app.kubernetes.io/instance: {{ .Name }}
    app.kubernetes.io/component: {{ .Component }}
  ports:
    - name: webhook
      port: 7000
      protocol: TCP
      targetPort: 7000
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
